refactoring/Update_to_project_keeper_5.0.0 (#58)
* #58: Adapted CI build to PK 5.0.0.
* #58: Switched runner OS to Ubuntu 24.04.
* #58: Switched the installation method of Luarocks from the GitHub action `leafo/gh-actions-luarocks` to using `apt-get`.

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -1,83 +1,234 @@
+# This file was generated by Project Keeper.
 name: CI Build
-
 on:
   push:
-    branches:
-      - main
+    branches: [
+      main
+    ]
+    
   pull_request:
-
+    types: [
+      opened,
+      synchronize,
+      reopened,
+      ready_for_review
+    ]
+    
+  workflow_dispatch: null
 jobs:
-  matrix-build:
-    name: Build with Lua ${{ matrix.lua_version }} using Exasol ${{ matrix.docker_db_version }}
-    strategy:
-      fail-fast: true
-      matrix:
-        lua_version: [5.4]
-        docker_db_version: ["7.1.25", "8.25.0"]
-    env:
-      DEFAULT_DB_VERSION: "8.25.0"
-    runs-on: ubuntu-22.04
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.lua_version }}-${{ matrix.docker_db_version }}
+  build-and-test:
+    runs-on: ubuntu-24.04
+    defaults:
+      run: {
+        shell: bash
+      }
+    permissions: {
+      contents: read,
+      issues: read
+    }
+    concurrency: {
+      group: '${{ github.workflow }}-build-and-test-${{ github.ref }}',
       cancel-in-progress: true
+    }
+    outputs: {
+      release-required: '${{ steps.check-release.outputs.release-required }}'
+    }
     steps:
       - name: Free Disk Space
+        id: free-disk-space
+        if: ${{ false }}
         run: |
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf /usr/share/dotnet
       - name: Checkout the repository
+        id: checkout
         uses: actions/checkout@v4
-        with:
+        with: {
           fetch-depth: 0
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: 17
-          cache: "maven"
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Install Lua ${{ matrix.lua_version }}
-        uses: leafo/gh-actions-lua@v10
-        with:
-          luaVersion: ${{ matrix.lua_version }}
-      - name: Install LuaRocks
-        uses: leafo/gh-actions-luarocks@v4
-        with:
-          luaRocksVersion: "3.9.1"
-      - name: Install Lua dependencies
+        }
+      - name: Install Lua, LuaRocks and Lua Dependencies
+        id: install-lua
         run: |
-          luarocks --local install --only-deps *.rockspec
-      - name: Enable testcontainer reuse
+          sudo apt-get install lua5.4 liblua5.4-dev luarocks
+          luarocks --version
+          mkdir -p "$HOME"/.luarocks
+          echo 'lua_version = "5.4"' > "$HOME"/.luarocks/config-5.4.lua
+          echo 'return "5.4"' > "$HOME"/.luarocks/default-lua-version.lua
+          luarocks --lua-version=5.4 --local path >> $GITHUB_ENV
+          luarocks --lua-version=5.4 --local install --only-deps *.rockspec
+      - name: Set up JDKs
+        id: setup-java
+        uses: actions/setup-java@v4
+        with: {
+          distribution: temurin,
+          java-version: '17',
+          cache: maven
+        }
+      - name: Cache SonarCloud packages
+        id: cache-sonar
+        uses: actions/cache@v4
+        with: {
+          path: ~/.sonar/cache,
+          key: '${{ runner.os }}-sonar',
+          restore-keys: '${{ runner.os }}-sonar'
+        }
+      - {
+        name: Enable testcontainer reuse,
+        id: enable-testcontainer-reuse,
         run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
+      }
       - name: Run tests and build with Maven
+        id: build-pk-verify
         run: |
           mvn --batch-mode clean verify \
-              -Dcom.exasol.dockerdb.image=${{ matrix.docker_db_version }} \
               -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
               -DtrimStackTrace=false
-      - name: Publish Test Report
-        uses: scacap/action-surefire-report@v1
-        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Create dummy error report
+        id: error-report
+        run: |
+          echo '{
+              "errorReportVersion" : "1.0",
+              "errorCodes": [
+                  {"identifier": "E-DUMMY-1"}
+              ]
+          }' > target/error_code_report.json
+      - {
+        name: Check shell scripts,
+        id: shell-check,
+        run: tools/shellcheck.sh
+      }
       - name: Sonar analysis
-        if: ${{ env.SONAR_TOKEN != null && env.DEFAULT_DB_VERSION == matrix.docker_db_version }}
+        id: sonar-analysis
+        if: ${{ env.SONAR_TOKEN != null }}
         run: |
           mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
               -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
               -DtrimStackTrace=false \
               -Dsonar.token=$SONAR_TOKEN
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-
-  build:
-    needs: matrix-build
+        env: {
+          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
+          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
+        }
+      - name: Verify Release Artifacts
+        id: verify-release-artifacts
+        run: "print_message() {\n    local -r message=$1\n    echo \"$message\"\n    echo \"$message\" >> \"$GITHUB_STEP_SUMMARY\"\n}\n\nprint_message \"### Release Artifacts\"\n\nIFS=$'\\n' artifacts_array=($ARTIFACTS)\nmissing_files=()\nfor file in \"${artifacts_array[@]}\";\ndo  \n    echo \"Checking if file $file exists...\"\n    if ! [[ -f \"$file\" ]]; then\n        print_message \"* ⚠️ \\`$file\\` does not exist ⚠️\"\n        echo \"Content of directory $(dirname \"$file\"):\"\n        ls \"$(dirname \"$file\")\"\n        missing_files+=(\"$file\")\n    else\n        print_message \"* \\`$file\\` ✅\" \n    fi\ndone\nprint_message \"\"\nnumber_of_missing_files=${#missing_files[@]}\nif [[ $number_of_missing_files -gt 0 ]]; then\n    print_message \"⚠️ $number_of_missing_files release artifact(s) missing ⚠️\"\n    exit 1\nfi\n"
+        env: {
+          ARTIFACTS: '${{ steps.build-pk-verify.outputs.release-artifacts }}'
+        }
+      - name: Upload artifacts
+        id: upload-artifacts
+        uses: actions/upload-artifact@v4
+        with: {
+          name: artifacts,
+          path: '${{ steps.build-pk-verify.outputs.release-artifacts }}',
+          retention-days: 5
+        }
+      - name: Configure link check
+        id: configure-link-check
+        run: |
+          mkdir -p ./target
+          echo '{"aliveStatusCodes": [429, 200], "ignorePatterns": [' \
+               '{"pattern": "^https?://(www|dev).mysql.com/"},' \
+               '{"pattern": "^https?://(www.)?opensource.org"}' \
+               '{"pattern": "^https?://(www.)?eclipse.org"}' \
+               '{"pattern": "^https?://projects.eclipse.org"}' \
+               ']}' > ./target/broken_links_checker.json
+      - uses: gaurav-nelson/github-action-markdown-link-check@v1
+        id: run-link-check
+        with: {
+          use-quiet-mode: yes,
+          use-verbose-mode: yes,
+          config-file: ./target/broken_links_checker.json
+        }
+  next-java-compatibility:
     runs-on: ubuntu-latest
+    defaults:
+      run: {
+        shell: bash
+      }
+    permissions: {
+      contents: read
+    }
+    concurrency: {
+      group: '${{ github.workflow }}-next-java-${{ github.ref }}',
+      cancel-in-progress: true
+    }
     steps:
-      - run: echo "Build successful"
+      - {
+        id: skipped-checkout,
+        run: echo "Skipped next-Java checkout - Lua project"
+      }
+      - {
+        id: skipped-setup-java,
+        if: '${{ false }}',
+        run: echo Skipped
+      }
+      - {
+        id: skipped-build-next-java,
+        if: '${{ false }}',
+        run: echo Skipped
+      }
+  build:
+    needs: [
+      build-and-test,
+      next-java-compatibility
+    ]
+    runs-on: ubuntu-latest
+    defaults:
+      run: {
+        shell: bash
+      }
+    permissions: {
+      contents: read,
+      issues: read
+    }
+    outputs: {
+      release-required: '${{ steps.check-release.outputs.release-required }}'
+    }
+    steps:
+      - name: Checkout the repository
+        id: checkout
+        uses: actions/checkout@v4
+        with: {
+          fetch-depth: 0
+        }
+      - name: Set up JDKs
+        id: setup-java
+        uses: actions/setup-java@v4
+        with: {
+          distribution: temurin,
+          java-version: '17',
+          cache: maven
+        }
+      - name: Check if release is needed
+        id: check-release
+        if: ${{ github.ref == 'refs/heads/main' }}
+        run: |
+          if mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify-release --projects .; then
+              echo "### ✅ Release preconditions met, start release" >> "$GITHUB_STEP_SUMMARY"
+              echo "release-required=true" >> "$GITHUB_OUTPUT"
+          else
+              echo "### 🛑 Not all release preconditions met, skipping release" >> "$GITHUB_STEP_SUMMARY"
+              echo "See log output for details." >> "$GITHUB_STEP_SUMMARY"
+              echo "release-required=false" >> "$GITHUB_OUTPUT"
+          fi
+        env: {
+          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
+        }
+  start_release:
+    needs: build
+    if: ${{ github.ref == 'refs/heads/main' && needs.build.outputs.release-required == 'true' }}
+    concurrency: {
+      cancel-in-progress: false,
+      group: release
+    }
+    secrets: inherit
+    permissions: {
+      contents: write,
+      actions: read,
+      issues: read
+    }
+    uses: ./.github/workflows/release.yml
+    with: {
+      started-from-ci: true
+    }
